//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub username: String,
    pub name: Option<String>,
    pub password_hash: String,
    pub role: String,
    pub show_in_weekly: bool,
    pub created_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::checkin::Entity")]
    Checkin,
}

impl Related<super::checkin::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Checkin.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
